/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package output;

public class Library {
	public static void main(String args[]) {
		OutputUIApplication.run(args);
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
